### ISSUE TITLE
[lfx] Develop Propagation policy, Settings, About Pages

### ISSUE THREAD

**Issue by chinmaym07** [karmada-io/dashboard#16]
**What would you like to be added**:
Develop & enhance the Propagation policy, Settings & About Pages for the Dashboard Project.

**Figma Design**: 
> https://www.figma.com/file/lEDkjr4gdIn35BSi1hXAGT/Karmada?node-id=261%3A2705

**Why is this needed**:
Propogation Policy page on the web dashboard will help to perform different operations for Propagation policies in karmada, Settings page will help the user to modify the dashboard according to their needs.

**Comment by SAEb-ai** [comment]
@chinmaym07 @RainbowMango I wish to contribute to this under the LFX mentorship program for the summer season. But before that I have a few questions regarding this project as mentioned below:

- Do we have to make this responsive?
- Do we have to write unit tests as well as end to end tests for this?
- Is there any backend work too for this project?  
- Do you have a communication channel(Slack, gitter, etc) so that I can introduce myself there?

It would be really helpful for me in writing the cover letter if you can please clarify my above queries. Thanks!!

**Comment by chinmaym07** [comment]
Hi @SAEb-ai  Thankyou for showing interest 💯.

1. Yes we will make it responsive.

2. Yes we will be having unit tests. E2E will be done later.

3. Most of the work will be using the API's provided by the kamada for different functionalities like login, CRUD operations for different type of resources. So you'll have to get a better understanding of the API's that you are using.

Yes we have a `#karmada` & `#karmada-dev` channel in [CNCF slack](https://cloud-native.slack.com/join/shared_invite/zt-18ufdlnhw-bPjsv_Qlwwm9cLL89JAfZw#/shared-invite/email). 

Please do reach out for any queries. I'll be happy to help. 
Thankyou 👍🏻

**Comment by Ciggzy1312** [comment]
Hey @chinmaym07 I too am interested in working on this issue under the LFX mentorship program for the summer season
Before applying should I be knowing anything else about the project or doing some specific homework of my own then please do let me know
Thank you

**Comment by hs-07** [comment]
Hello ! @chinmaym07 .
I had understood the project issues & ready to contribute in the Project.
I had saw the figma design and the UI looking great.
Recently, I tried to run the project locally but failed, so i request you to plz guide me so that i could start working over it.
Thankyou

**Comment by RainbowMango** [comment]
@rgrupesh Please assign this issue to yourself by command
/assign @rgrupesh
